# Generated by Django 3.0.8 on 2021-05-31 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='process',
        ),
    ]
