# Generated by Django 3.0.8 on 2021-05-31 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_delete_process'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ord_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='ord_qty',
            field=models.BigIntegerField(),
        ),
    ]
