# Generated by Django 3.0.8 on 2021-06-08 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_auto_20210601_0710'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ord_qty',
        ),
    ]
