# Generated by Django 3.0.8 on 2021-06-10 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_remove_order_ord_qty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='tot_price',
            new_name='item_price',
        ),
    ]
