# Generated by Django 3.0.8 on 2021-06-10 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_auto_20210610_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_detail',
            name='item_price',
        ),
    ]
