# Generated by Django 3.0.8 on 2021-06-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_remove_order_detail_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_detail',
            name='item_price',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True),
        ),
    ]
