# Generated by Django 3.0.8 on 2021-06-10 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_order_detail_item_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_detail',
            old_name='item_price',
            new_name='itm_price',
        ),
        migrations.RemoveField(
            model_name='order_detail',
            name='pay_mode',
        ),
    ]
