# Generated by Django 3.0.8 on 2021-06-13 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_auto_20210610_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_detail',
            name='itm_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
